baseURL = 'https://marchvidkjaer.com/'
languageCode = 'en-us'
title = 'My marchvidkjaer.com site'
publishDir = "docs"
enableGitInfo = true


[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

